version: '3'

services:

  redis: 
    image: redis
    networks:
      - bayt-network

  backend:
    build: ./server
    restart: always
    depends_on:
       - redis
    #ports:
     # - 7000:7000
    networks:
      - bayt-network

  frontend:
    build: ./client
    restart: always

    #ports:
      #- 3000:3000
    depends_on:
      - backend
      - redis
    networks:
      - bayt-network

  nginx:
    build: ./nginx
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 80:80
    networks:
      - bayt-network

networks:
  bayt-network:
    driver: bridge
