version: '3'
#docker-compose -f docker-compose-dev.yml up --build 
services:
  redis: 
    build: ./redis
    networks:
      - bayt-network

  backend:
    build: ./server
    restart: always
    depends_on:
       - redis
    ports:
      - "4000:4000"
      - "9000:9000"
    networks:
      - bayt-network

networks:
  bayt-network:
    driver: bridge

