version: '3'

services:

  redis: 
    build: ./redis
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/redis:latest
    networks:
      - bayt-network

  backend:
    build: ./server
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/backend:latest
    restart: on-failure
    depends_on:
       - redis
    ports:
      - "4000:4000"
      - "9000:9000"
    networks:
      - bayt-network


networks:
  bayt-network:
    driver: bridge
