version: '3'

services:

  redis: 
    build: ./redis
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/redis
    networks:
      - app-network

  backend:
    build: .
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/backend
    restart: always
    depends_on:
       - redis
    ports:
      - 4000:4000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
