on:
  push:
    branches: [ main ]

name: Deploy to AWS ECR

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push the image to Amazon ECR
      id: build-image
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
          # Build a docker container and push it to ECR 
          docker-compose -f "docker-compose.yml" build
          echo "Pushing image to ECR..."
          docker-compose -f "docker-compose.yml"  push
          echo "Image has been pushed to AWS ECR"
    
  